---
name: "Update Modules base"

on:
  workflow_dispatch:

jobs:
  update-Modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Firmware
        uses: actions/checkout@v4 # v4

      - name: Get Github App Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure Git User and E-Mail
        run: git config --global user.name "${{ env.COMMIT_NAME }}" && git config --global user.email "${{ env.COMMIT_EMAIL }}"
        env:
          COMMIT_NAME:  ${{ steps.app-token.outputs.app-slug }}[bot] 
          COMMIT_EMAIL: ${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com

      - name: Get update branch name
        id: branch-name
        run: echo "branch-name=update-modules-${{ github.ref_name }}-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Invoke update-modules
        run: ./contrib/actions/update-modules.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: '[${{ github.ref_name }}] update modules'
          body: |
            Update modules for ${{ github.ref_name }} branch
            <sub><sup>- Auto-generated by [create-pull-request][1]</sub></sup>

            [1]: https://github.com/peter-evans/create-pull-request
          branch: ${{ steps.branch-name.outputs.branch-name }}
          labels: ${{ github.ref_name }}
          draft: true # this step does not trigger a CI run, so always mark them as draft
          delete-branch: true

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
